version: '3.8'

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  proxene:
    build: .
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=INFO
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./policies:/app/policies
      - ./logs:/app/logs

  dashboard:
    build: 
      context: .
      dockerfile: Dockerfile.dashboard
    restart: unless-stopped
    ports:
      - "8501:8501"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./dashboard:/app/dashboard

volumes:
  redis_data: